-- Insertion de propriétés de test
INSERT OR IGNORE INTO properties (title, description, type, transaction_type, price, area, rooms, bedrooms, bathrooms, address, city, postal_code, features, year_built, image_url) VALUES 
(
  'Appartement moderne au centre-ville',
  'Magnifique appartement entièrement rénové avec vue panoramique. Proche de toutes commodités, transports en commun à 2 minutes. Cuisine équipée, double vitrage, chauffage au sol.',
  'appartement',
  'vente',
  285000,
  85,
  4,
  2,
  1,
  '15 Rue de la République',
  'Lyon',
  '69002',
  '["parking", "balcon", "ascenseur", "cave", "double_vitrage", "cuisine_equipee"]',
  2018,
  'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'
),
(
  'Villa avec piscine et jardin',
  'Superbe villa individuelle de plain-pied avec piscine chauffée et grand jardin paysager. 4 chambres spacieuses, salon cathédrale, cuisine américaine. Garage double, portail automatique.',
  'villa',
  'vente',
  650000,
  180,
  6,
  4,
  3,
  '8 Allée des Pins',
  'Aix-en-Provence',
  '13100',
  '["piscine", "jardin", "garage", "terrasse", "climatisation", "cheminee"]',
  2015,
  'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800'
),
(
  'Studio lumineux quartier latin',
  'Charmant studio rénové de 28m² idéal étudiant ou investissement locatif. Parfait état, cuisine aménagée, salle d''eau moderne. Au calme, 5ème étage avec ascenseur.',
  'studio',
  'location',
  850,
  28,
  1,
  0,
  1,
  '22 Rue Mouffetard',
  'Paris',
  '75005',
  '["meuble", "ascenseur", "cuisine_equipee", "fibre_optique"]',
  2019,
  'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'
),
(
  'Maison de ville avec terrasse',
  'Belle maison de ville sur 3 niveaux avec terrasse tropézienne. Séjour lumineux, 3 chambres, bureau. Cave et parking privatif. Quartier résidentiel calme.',
  'maison',
  'vente',
  445000,
  125,
  5,
  3,
  2,
  '33 Avenue Victor Hugo',
  'Bordeaux',
  '33200',
  '["terrasse", "parking", "cave", "alarme", "volets_electriques"]',
  2010,
  'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800'
),
(
  'Appartement neuf avec balcon',
  'Appartement T3 neuf avec prestations haut de gamme. Balcon 15m², parking en sous-sol, cellier. Résidence sécurisée avec espaces verts. Livraison immédiate.',
  'appartement',
  'vente',
  320000,
  72,
  3,
  2,
  1,
  '5 Rue des Jardins',
  'Nantes',
  '44000',
  '["parking", "balcon", "ascenseur", "neuf", "interphone", "digicode"]',
  2024,
  'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'
),
(
  'Bureau moderne centre d''affaires',
  'Espace de bureau modulable de 150m² dans immeuble contemporain. Open space, 2 salles de réunion, kitchenette. Fibre optique, climatisation réversible.',
  'bureau',
  'location',
  2800,
  150,
  5,
  0,
  2,
  '10 Boulevard des Entreprises',
  'Toulouse',
  '31000',
  '["parking", "ascenseur", "climatisation", "fibre_optique", "acces_handicape"]',
  2020,
  'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800'
),
(
  'Loft industriel rénové',
  'Exceptionnel loft de 110m² dans ancienne usine réhabilitée. Volumes spectaculaires, hauteur sous plafond 4m, poutres apparentes. Quartier branché, proche métro.',
  'appartement',
  'location',
  1650,
  110,
  3,
  2,
  1,
  '18 Rue de la Manufacture',
  'Lille',
  '59000',
  '["parking", "cave", "poutres_apparentes", "grande_hauteur", "lumineux"]',
  2017,
  'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800'
),
(
  'Mas provençal avec vue mer',
  'Authentique mas provençal entièrement restauré avec piscine à débordement et vue mer panoramique. 5 chambres, pool house, terrain 2500m². Prestations d''exception.',
  'villa',
  'vente',
  1250000,
  280,
  8,
  5,
  4,
  'Chemin des Oliviers',
  'Saint-Tropez',
  '83990',
  '["piscine", "jardin", "vue_mer", "climatisation", "cheminee", "garage"]',
  1850,
  'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800'
);

-- Quelques demandes de renseignements
INSERT OR IGNORE INTO inquiries (property_id, name, email, phone, message, status) VALUES
(1, 'Marie Dupont', 'marie.dupont@email.com', '0612345678', 'Bonjour, je suis intéressée par cet appartement. Est-il possible de le visiter ce week-end ?', 'nouveau'),
(2, 'Jean Martin', 'jean.martin@email.com', '0623456789', 'La villa est-elle toujours disponible ? Puis-je avoir plus d''informations sur le quartier ?', 'en_cours'),
(3, 'Sophie Bernard', 'sophie.bernard@email.com', '0634567890', 'Je recherche un studio pour ma fille étudiante. Quand serait-il disponible ?', 'nouveau');
